### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by Fermec28**
Fixing FileStorage

### CODE REVIEW

**Review by yawzyag — CHANGES_REQUESTED** [review]
Please Erase the .pyc files
I advise you to use a .gitignore file

**Comment by Fermec28** [comment]
removed files

**Review by yawzyag — COMMENTED** [review]
Ready for merge, pls Check pep8

**Comment by Fermec28** [comment]
already pep8 checked  :1st_place_medal:

**Review by yawzyag — APPROVED** [review]
Great 🥇

**Pull request merged**
